apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "2"
  creationTimestamp: 2018-11-26T12:51:35Z
  generation: 3
  labels:
    run: demo-web-app
  name: demo-web-app
  namespace: default
  resourceVersion: "3255"
  selfLink: /apis/extensions/v1beta1/namespaces/default/deployments/demo-web-app
  uid: 019daec9-f17a-11e8-beca-080027ff8689
spec:
  progressDeadlineSeconds: 600
  replicas: 2
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      run: demo-web-app
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: demo-web-app
    spec:
      containers:
      - image: manjula/lk.cloud.meetup.k8s.tomcat-app:2.0.0
        readinessProbe:
                tcpSocket:
                 port: 8080
                initialDelaySeconds: 5
                periodSeconds: 10
        imagePullPolicy: IfNotPresent
        name: demo-web-app
        ports:
        - containerPort: 8080
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 2
  conditions:
  - lastTransitionTime: 2018-11-26T13:01:46Z
    lastUpdateTime: 2018-11-26T13:01:46Z
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: 2018-11-26T12:51:35Z
    lastUpdateTime: 2018-11-26T13:04:43Z
    message: ReplicaSet "demo-web-app-79f8fd8c7c" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 3
  readyReplicas: 2
  replicas: 2
  updatedReplicas: 2
